hmpps-auth:
  url: "http://localhost:8090/auth"

prison-api:
  url: "http://localhost:8091"


spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/reconciliation_db?sslmode=prefer'
    username: reconciliation
    password: reconciliation
    hikari:
      pool-name: RECON-DB-CP
  #      maximum-pool-size: 10
  #      connection-timeout: 30000
  #      validation-timeout: 5000
  flyway:
    url: jdbc:postgresql://localhost:5432/reconciliation_db?sslmode=prefer
    user: reconciliation
    password: reconciliation
